import type {
  SpriteAnimations,
  SpriteAnimationsMeta,
  SpriteFrame as RenderSpriteFrame,
} from '../SpriteAnimator';

/**
 * SpriteFrame extension that includes a stable identifier required by editor features.
 */
export interface SpriteEditorFrame extends RenderSpriteFrame {
  /** Stable identifier generated by the editor. */
  id: string;
}

/**
 * Metadata stored alongside the editor state.
 */
export interface SpriteEditorMeta {
  /** Human-readable sprite name displayed by editors. */
  displayName?: string;
  [key: string]: unknown;
}

/**
 * Selection tracks the ids of frames that are currently highlighted in the editor UI.
 */
export type SpriteEditorSelection = string[];

/**
 * Snapshot stored inside the undo/redo stacks.
 */
export interface SpriteEditorSnapshot {
  /** Ordered frame definitions used by the editor and runtime. */
  frames: SpriteEditorFrame[];
  /** Animation sequences keyed by name. */
  animations: SpriteAnimations;
  /** Optional per-animation metadata overrides. */
  animationsMeta?: SpriteAnimationsMeta;
  /** Animation selected for autoplay when exported. */
  autoPlayAnimation?: string | null;
  /** Frame ids currently selected inside the editor UI. */
  selected: SpriteEditorSelection;
  /** Arbitrary metadata persisted alongside the sprite. */
  meta: SpriteEditorMeta;
}

/**
 * Full editor state including clipboard + history buffers.
 */
export interface SpriteEditorState extends SpriteEditorSnapshot {
  /** Frames stored inside the clipboard buffer for paste operations. */
  clipboard: SpriteEditorFrame[];
  /** Past snapshots used for undo operations. */
  history: SpriteEditorSnapshot[];
  /** Future snapshots used for redo operations. */
  future: SpriteEditorSnapshot[];
}
